apiVersion: apps/v1
kind: Deployment
metadata:
  name: icargo-app
  labels:
    app: icargo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: icargo
  template:
    metadata:
      labels:
        app: icargo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: icargo
          image: ghcr.io/kirubanithi10/devops-python-app:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
